default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: cd_hms_development

test:
  <<: *default
  database: cd_hms_test

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['APP_DATABASE_DATABASE'] %>
  username: <%= ENV['APP_DATABASE_USERNAME'] %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
