# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6cc991a893a4f5b8b1c02f83e4f996eaa91c8b168e41fce00dbc0b1356a141b89aa6999b1570396d1e263e916c407db5b3c45032399c3ef07d2707811e9ffb6

test:
  domain: example.com
  google_client_id: test
  google_client_secret: test
  secret_key_base: c4c9c191fe6dff1243c00005c00b0abd85ffe24aeb91dbf622406a2f22068b81ad99729bb47e4f0fd4fc8e8b320288ba30341a27e650ed583736f3cb627d49df
  token: 35809e414b3c523f14f10e6b0f51c1763e2b9e98ec432408c8dcaa1a77a43534b928f05f3494278cc3ec598674877620f962f90770f9298fe1e80aa1422150f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain: <%= ENV['DOMAIN'] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  token: <%= ENV['TOKEN'] %>
